import {
  AUTOMATION_RULE_ENDPOINT_SLOT,
  AUTOMATION_RULE_INPUT_SLOT,
  AUTOMATION_RULE_OUTPUT_SLOT,
} from '@src/config'
import {
  AutomationDetailCreateRequest,
  AutomationConnectionCreateRequest,
  AutomationExecutionCreateRequest,
  AutomationExecutionType,
  AutomationGateway,
  AutomationPrimitiveState,
  AutomationRuleDeviceCondition,
  AutomationSceneCreateRequest,
  AutomationSceneUpdateRequest,
} from './type'

const randomByte = () => Math.floor(Math.random() * 256)

const randomMac = () =>
  [0x02, randomByte(), randomByte(), randomByte(), randomByte(), randomByte()]
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join(':')

export const createAutomationGatewayData = (
  mac = randomMac(),
): AutomationGateway => ({
  mac,
  address: '127.0.0.1',
  active_automation: true,
})

export const createAutomationExecutionData = (
  type: AutomationExecutionType,
): AutomationExecutionCreateRequest => ({
  type,
  input: {
    '0': {
      condition: '==',
      value: true,
    },
    '1': {
      condition: '==',
      value: false,
    },
  },
  output: {
    '0': true,
  },
})

export const createAutomationDetailData = ({
  type,
  inputs,
  outputs,
  enable = true,
  name = `auto_rule_api_${Date.now()}`,
  description = 'Automation rule generated by e2e test',
  startTime = null,
  endTime = null,
}: {
  type: AutomationExecutionType
  inputs: Array<{
    id: string | number
    status: AutomationPrimitiveState
    slot?: number
    endpointSlot?: number
  }>
  outputs: Array<{
    id: string | number
    status: AutomationPrimitiveState
    slot?: number
    endpointSlot?: number
  }>
  enable?: boolean
  name?: string
  description?: string | null
  startTime?: string | null
  endTime?: string | null
}): AutomationDetailCreateRequest => ({
  automation: {
    name,
    description,
    enable,
    start_time: startTime,
    end_time: endTime,
  },
  execution: {
    type,
    input: inputs.map((input, index) =>
      toRuleDeviceCondition(input, AUTOMATION_RULE_INPUT_SLOT + index),
    ),
    output: outputs.map((output) =>
      toRuleDeviceCondition(output, AUTOMATION_RULE_OUTPUT_SLOT),
    ),
  },
})

export const createAutomationConnectionData = (
  sourceId: number,
  targetId: number,
): AutomationConnectionCreateRequest => ({
  source: {
    id: sourceId,
    slot: 0,
  },
  target: {
    id: targetId,
    slot: 0,
  },
  transformer: null,
})

const toRuleDeviceCondition = (
  device: {
    id: string | number
    status: AutomationPrimitiveState
    slot?: number
    endpointSlot?: number
  },
  defaultSlot: number,
): AutomationRuleDeviceCondition => ({
  id: device.id,
  status: device.status,
  slot: device.slot ?? defaultSlot,
  endpoint_slot: device.endpointSlot ?? AUTOMATION_RULE_ENDPOINT_SLOT,
})

export const createAutomationSceneData = (
  bindingId: number,
): AutomationSceneCreateRequest => ({
  type: 'Normal',
  name: `auto_scene_${Date.now()}`,
  icon: 'automation-test',
  enable: true,
  background: null,
  background_color: '#ffffff',
  binding: [
    {
      id: String(bindingId),
      snapshot: {
        '1': true,
      },
      status: 'Updating',
    },
  ],
  cron: null,
  cron_enable: false,
})

export const createRealHcSceneData = ({
  deviceId,
  slot,
  value,
}: {
  deviceId: string
  slot: string
  value: boolean
}): AutomationSceneCreateRequest => ({
  type: 'Normal',
  name: `AUTO_SCENE_E2E_${Date.now()}`,
  icon: '-1',
  enable: true,
  background: null,
  background_color: '#ffffff',
  binding: [
    {
      id: deviceId,
      snapshot: {
        [slot]: value,
      },
      status: 'Activated',
    },
  ],
  cron: null,
  cron_enable: false,
})

export const createRealHcSceneUpdateData = ({
  name,
  deviceId,
  slot,
  value,
}: {
  name: string
  deviceId: string
  slot: string
  value: boolean
}): AutomationSceneUpdateRequest => ({
  name,
  binding: [
    {
      id: deviceId,
      snapshot: {
        [slot]: value,
      },
      status: 'Activated',
    },
  ],
})
