node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"
  data_dir = "/opt/emqx/data"
  db_backend = mnesia
}

cluster {
  proto_dist = inet_tcp
}

dashboard {
  listeners.http {
    bind: 18083
  }

  default_username = "admin"
  default_password = "lumivn274"
}

actions {
  http {
    client_hc_status_connection_WH_D {
      enable = true
      connector = client_hc_status_connection_WH_D

      parameters {
        method = post
        max_retries = 2

        headers {
          content-type = "application/json"
        }
      }

      resource_opts {
        query_mode = async
        worker_pool_size = 16
        inflight_window = 100
        max_buffer_bytes = "256MB"
        request_ttl = "45s"
        health_check_interval = "15s"
      }
    }
  }
}

connectors {
  http {
    client_hc_status_connection_WH_D {
      enable = true
      url = "http://iot-console:3333/api/v0/internal/mqtt/hooks/connection"

      connect_timeout = "15s"
      enable_pipelining = 100
      pool_size = 8
      pool_type = random

      headers {
        content-type = "application/json"
        x-iot-hook-key = "8dlvRb4jJw6eeBAk4wp6SWc6beQWERTY"
      }

      resource_opts {
        start_after_created = true
        start_timeout = "5s"
        health_check_interval = "15s"
      }

      ssl {
        enable = false
        verify = verify_none
        reuse_sessions = true
        secure_renegotiate = true
        hibernate_after = "5s"
        log_level = notice
        depth = 10
        ciphers = []

        versions = [
          "tlsv1.3",
          "tlsv1.2"
        ]
      }
    }
  }
}

rule_engine {
  ignore_sys_message = true
  jq_function_default_timeout = "10s"

  rules {
    client_hc_status_connection_WH_D {
      enable = true

      sql = """
        SELECT
          *
        FROM
          "$events/client_connected",
          "$events/client_disconnected"
      """

      actions = [
        "http:client_hc_status_connection_WH_D"
      ]
    }
  }
}